name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  Project_Name: Econ-Toolbox.Desktop.csproj

jobs:
  CI:
    runs-on: windows-latest                         
    env:
      Solution_Name: Econ-Toolbox.Desktop.sln                                  
      dotnet-version: '9.0.x'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup .NET Core SDK ${{ env.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: ${{ env.dotnet-version }} 

    - name: Create version number
      shell: pwsh
      run: |
        $VERSION = "0.0.0.${{ github. run_number }}-Beta"
        echo "VERSION=$VERSION" >> $env:GITHUB_ENV
      
    - name: Publish
      shell: pwsh
      run: |
        $PUBLISH_OUT = "${pwd}/TO-PACKAGE/"
        echo "PUBLISH_OUT=$PUBLISH_OUT" >> $env:GITHUB_ENV
        dotnet publish -c Release -v quiet /p:Version=${{ env.VERSION }} -o $PUBLISH_OUT ${{ env.PROJECT_NAME }} --self-contained true

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: HEC-FDA-${{ env.VERSION }}
        path: ${{ env.PUBLISH_OUT }}
